[env]

[esp8266]
board = d1_mini
platform = espressif8266
extra_lib_dirs = ../shared/src

build_src_flags = 
    -D HEARTBEAT_INTERVAL_MS=30000
    -D SENSOR_TIMEOUT_MS=300000
    -D PAIR_BUTTON_GPIO=0
    -D STATUS_LED_GPIO=2
build_flags = 
    -D MQTT_HOST_DEFAULT=\"192.168.1.12\"
    -D MQTT_PORT_DEFAULT=1883
    -D MQTT_USER_DEFAULT=\"kzuca\"
    -D MQTT_PASS_DEFAULT=\"123\"    

lib_deps = 
    bblanchon/ArduinoJson@^7.2.1
    knolleary/PubSubClient@^2.8
    