#ifndef HW_SHARED_SENSOR_TYPE_H
#define HW_SHARED_SENSOR_TYPE_H

#include <stdint.h>

typedef enum : uint8_t {
    SENSOR_TYPE_TEMP_HUM = 1,
    SENSOR_TYPE_CONTACT = 2,
    SENSOR_TYPE_MOTION = 3,
    SENSOR_TYPE_GAS = 4,
    SENSOR_TYPE_RAIN = 5,
    SENSOR_TYPE_TANK = 6,
    SENSOR_TYPE_DHT_GAS = 7,
    SENSOR_TYPE_ONOFF = 8,
    SENSOR_TYPE_LIGHT = 9,
    SENSOR_TYPE_REPEATER = 10,
    SENSOR_TYPE_DHT_RELE = 11,
    SENSOR_TYPE_SOIL_MOISTURE = 12,
} sensor_type_t;

#endif
