#ifndef HW_SHARED_CONFIG_H
#define HW_SHARED_CONFIG_H

#include <Arduino.h>

// Configuracao minima compartilhada entre gateway e clients para o
// myWiFiManager e espnow_protocol. Mantenha IGUAL em todos os devices.

#define WIFI_MODE_DHCP 0
#define WIFI_MODE_STATIC 1

#define EEPROM_SIZE 512
#define EEPROM_WIFI_SSID_OFFSET 0
#define EEPROM_WIFI_SSID_SIZE 33
#define EEPROM_WIFI_PASS_OFFSET (EEPROM_WIFI_SSID_OFFSET + EEPROM_WIFI_SSID_SIZE)
#define EEPROM_WIFI_PASS_SIZE 65
#define EEPROM_WIFI_MODE_OFFSET (EEPROM_WIFI_PASS_OFFSET + EEPROM_WIFI_PASS_SIZE)
#define EEPROM_WIFI_MODE_SIZE 1
#define EEPROM_WIFI_IP_OFFSET (EEPROM_WIFI_MODE_OFFSET + EEPROM_WIFI_MODE_SIZE)
#define EEPROM_WIFI_IP_SIZE 16
#define EEPROM_WIFI_GW_OFFSET (EEPROM_WIFI_IP_OFFSET + EEPROM_WIFI_IP_SIZE)
#define EEPROM_WIFI_GW_SIZE 16
#define EEPROM_WIFI_MASK_OFFSET (EEPROM_WIFI_GW_OFFSET + EEPROM_WIFI_GW_SIZE)
#define EEPROM_WIFI_MASK_SIZE 16
#define EEPROM_WIFI_DNS_OFFSET (EEPROM_WIFI_MASK_OFFSET + EEPROM_WIFI_MASK_SIZE)
#define EEPROM_WIFI_DNS_SIZE 16

#define WIFI_CONFIG_PORTAL_SSID "ESPNOW_Setup"
#define WIFI_CONFIG_PORTAL_PASS "password123"

#define ESP_NOW_CHANNEL 1

#define FW_VERSION "v0.0.25"

#endif
